---
title: "**Instruções dos Scripts em R**"
author: "Guilherme Gloriano"
date: "07/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scripts Implementados:

01) graph_all_variables
02) graph_mult_bar
03) graph_mult_line
04) graph_pms
05) graph_test_plotly
06) media_15min_inverter
07) media_15min_inverter2_joinfilesInOne
08) media_15min_inverter3_allfiles
09) media_15min_station
10) media_15min_station2_joinfilesInOne
11) media_15min_station3_allfile2s
12) media_15min_station3_allfiles
13) merge_Station_Inverter_daily
14) merge_Station_Inverter_month
15) time_shift_23Out_05Nov


## Roteiros de Uso:

* Fazer o download das tabelas do inversor e estação e colocar em suas devidas pastas:
  + inversor_diario_min
  + ambientais_diario_min
  
* Criar os arquivos com as médias de 15 minutos, reduzindo a quantidade de amostras para as tabelas do inversor e estação (respectivamente).
  + utilizar os scripts:
      + media_15min_inverter3_allfiles
      + media_15min_station3_allfiles
      
* Passar o script que corrige a defasagem das amostras, causada pela modificação do horário de verão (apenas os dados do inversor apresentam este problema de deslocamento):
  + time_shift_23Out_05Nov
  
* Após os arquivos contendo os intervalos de 15 minutos serem criados (para inversor e estação) e ter corrigido a falta de sincronismo (apenas no inversor), usar o código que combina as duas tabelas em arquivos diários:
  + merge_Station_Inverter_daily
  
* Após as tabelas serem combinadas, gerar o gráfico desejado para a análise.
  + ex: graph_all_variables





## Breve Explicação de Cada Script:





#### **1. graph_all_variables**

Script responsável para criação dos gráficos de linhas contendo todas variáveis ambientais e de produção. Este script deve ser usado somente após a criação dos arquivos diários combinados (Estação/Inversor) no intervalo de 15 minutos.




#### **2. graph_mult_bar**

Esse script realiza a criação dos gráficos de barras de um conjunto de variáveis. Necessário apenas selecionar quais campos devem ser plotados.



#### **3. graph_mult_line**
Uma especificação do código >>> *1. graph_all_variables* <<<. Criado para realização de plotagens de teste.




#### **4. graph_pms**
Script responsável pela plotagem das informações obtidas pelo sensor de particulados, em forma de gráfico de linha. 



#### **5. graph_test_plotly**
Esse script gera gráficos de barras utilizando a função 'plotly' ao invés do 'ggplot'. Essa função gera arquivos **.html** e gráficos iterativos. Pode ser uma ferramenta útil para análise de dados futuros.



#### **6. media_15min_inverter**
Script responsável pela geração das médias no intervalo de 15 minutos dos dados do inversor. Este script gera os dados de média de apenas um único dia pré-especificado no início do código.



#### **7. media_15min_inverter2_joinfilesInOne**
Neste script todos os arquivos do inversor tem a escala de dados modificadas de 1 em 1 minuto, para 15 em 15 minutos e salva todos os arquivos lidos em um único arquivo **.csv**. Útil para a unificação de vários dias em um único documento.



#### **8. media_15min_inverter3_allfiles**
Modifica TODOS os arquivos, resultando em um **.csv** com as médias de 15 minutos dos dados do inversor. 




#### **9. media_15min_station **
Script responsável pela geração das médias no intervalo de 15 minutos dos dados da estação. Este script gera os dados de média de apenas um único dia pré-especificado no início do código.



#### **10. media_15min_station2_joinfilesInOne**
Neste script todos os arquivos da estação tem a escala de dados modificadas de 1 em 1 minuto, para 15 em 15 minutos e salva todos os arquivos lidos em um único arquivo **.csv**. Útil para a unificação de vários dias em um único documento.



#### **11. media_15min_station3_allfile2s**
Não lembro a modificação que estava sendo feita nesse código. Conferir depois porque não faço ideia o que ele faz.



#### **12. media_15min_station3_allfiles**
Modifica TODOS os arquivos, resultando em um **.csv** com as médias de 15 minutos dos dados da estação. 



#### **13. merge_Station_Inverter_daily**
Combina os arquivos da estação e inversor com intervalos já modificados em arquivos **.csv** diários. 


#### **14. merge_Station_Inverter_month**
Combina os arquivos da estação e inversor com intervalos já modificados em arquivos **.csv** mensais. 


#### **15. time_shift_23Out_05Nov**
Script responsável pelo deslocamento de 1hr no intervalo de 23 de Outubro de 2019 à 05 de Novembro de 2019. 

Obs: Esse script depende dos arquivos dos inversor no intervalo de 15 minutos já criado.


